### ISSUE TITLE
Failed to parse abi: abi: purely anonymous or underscored field is not supported

### ISSUE THREAD

**Issue by 0x19** [unpackdev/solgo#149]
Can be invoked by parsing ABI for contract: `0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0`

**Comment by 0x19** [comment]
Functions that start with _ are not supported. In order to sort this out we have to ensure only EXTERNAL and PUBLIC visibility types are packed for ABI. Internal and private functions/vars, etc... should not be in the ABI 😂

**Comment by shinewu-smlxl** [comment]
We are hit by this issue lately. Do we have an estimate of when this will land in the main release?

**Comment by 0x19** [comment]
@shinewu-smlxl Next release is targeted for end of January. What I can do is by EOW put the fixes into the main branch.
