### ISSUE TITLE
[Bug] Parsing does not handle single statement `if` Statements

### ISSUE THREAD

**Issue by xianlinc** [unpackdev/solgo#202]
### Problem
Parsing of `ast` tree does not handle the case where the `statementContext.Block() != nil` and `statementContext.Empty() == false`. This happens when we have a single statement if statement such as `if (block.timestamp <= time) revert TooLate(time);`.

### Suggestion
Add a line to handle that case in `ast/if.go`:
https://github.com/unpackdev/solgo/blob/87b65765ed0f5a26b0b1904c65a1bc2c9b69cd67/ast/if.go#L191

**Comment by 0x19** [comment]
@xianlinc do you have contract or address that I can use do build tests on?

**Comment by xianlinc** [comment]
yep! This contract from the solidity docs has one
https://docs.soliditylang.org/en/latest/solidity-by-example.html#simple-open-auction
