### ISSUE TITLE
Missing `NameLocation` field for declaration

### ISSUE THREAD

**Issue by zfy0701** [unpackdev/solgo#93]
Very nice project, but seems it lacks `nameLocation` field for declarations, which is the location just for  the identifier

**Comment by 0x19** [comment]
Hey @zfy0701 thank you!

There's a https://github.com/unpackdev/solgo/blob/main/ast/src.go which basically provides a way to extract identifier locations. Do you have any specific example that was not working?

**Comment by zfy0701** [comment]
srcNode  specific a code range, but it doesn't neccesary to be the identifier code range.

take a function node for example, it's src is the entire function block, not the identifier. that's why in newer soldity version, some node has two `SrceNode`, e.g.

```
export interface MemberAccess {
  src: SourceLocation;
  memberLocation?: string;
  ...
}
```
export interface VariableDeclaration {
  src: SourceLocation;
  nameLocation?: string;
 ...
}

same for other definition nodes, the defintion is from from https://www.npmjs.com/package/solidity-ast?activeTab=code (types.d.ts)

you can see example here in your own repo:
https://github.com/unpackdev/solgo/blob/139d75534ad2a16f3a0f11d66fbca0040f82a864/data/tests/contracts/cheelee/test.sol.ast.json#L177

**Comment by 0x19** [comment]
I see. Thank you very much for detailed explanation. Created new branch and will resolve this issue in upcoming PR.

**Comment by 0x19** [comment]
You're totally right! I've missed that portion entirely. What I see is in mappings that KeyNameLocation is missed as well.

**Comment by 0x19** [comment]
@zfy0701 thanks again for this very important missing info. I've resolved `NameLocation`, `KeyNameLocation`, `ValueNameLocation` and `MemberLocation` and should be good now to go.
